# Configuración optimizada para alta carga
listener 1883
allow_anonymous true

# Ajustes de persistencia y memoria
persistence false
# Si planeas escalar a 100k+, desactiva la persistencia para evitar I/O de disco.

# Limites de conexión y mensajes
# max_connections -1
# -1 significa que el broker no limita internamente, dependerá del OS.

# Ajustar tamaño de cola para evitar pérdida de datos
max_queued_messages 200000
max_inflight_messages 100

# Timeout para conexiones persistentes (Keepalive)
# Un intervalo mayor reduce la carga de paquetes de control (heartbeats)
#persistence_period 0
# Desactiva el guardado periódico si no es necesario.